---
title: "Women+ ECR Symposium"
---

On the **6^th^ of March** **2026,** to celebrate International Women’s Day, we will hold our first *Women+ in Early Career Research Symposium* at TU Dublin's city campus. The aim of this symposium is to create a supportive, inclusive space to showcase research, foster cross-disciplinary dialogue, and build networks among women and gender-diverse researchers at early career stages.

We invite paper submissions from **early-career women+ researchers** across disciplines, including STEM, humanities, health, creative practice, and interdisciplinary work. We especially encourage submissions from researchers whose voices are underrepresented in academia, including those from marginalized backgrounds, caregiving roles, regional institutions, and non-traditional career pathways.

Due to the interdisciplinary nature of the symposium, researchers outside your field may be reviewing your paper; for this reason, we ask all papers, presentations, and posters to be pitched at a broad scientific audience level. All accepted papers will be published on [Arrow](https://arrow.tudublin.ie/) TU Dublin’s Open Access institutional repository. There will be no charge for publishing on Arrow.

## Who Can Submit

-   Early career researchers including but not limited to PhD candidates, postdoctoral researchers or those in their first 10 years of research

-   Women and gender-diverse researchers (including trans, non-binary, genderqueer)

-   Researchers from any institution or discipline on the Island of Ireland

## Presentation Formats

-   Lightning talks (5 min)\
-   1st-year PhD track (5 min)\
-   Oral presentations (10 min)\
-   Posters

## Submissions

**Length:**\
1–3 pages (including references)

**Style:**\
Submissions should be written as an accessible science communication piece for a broad scientific audience.

<span id="Format"></span>
**Format:**\
Please use the LaTeX template provided. [⬇ Download the LaTeX template](assets/womenplus_ecr_latex.zip){.btn .btn-primary}
Please note once you download the template please upload the zip to Overleaf (or whatever you use to open Latex files). There is a "Source" folder and a "write in this folder", you should edit the "UseMe.tex" to write your submission. The "Source" folder will give it structure for you. You may wish to upload a .bib file if you wish to add references. When you are ready to submit recompile your latex document and download a pdf for submission.

**Research Areas:**\
Research area tells us what areas you feel represents your submission best. We accept submissions for all areas such as (but not limited to:)


- **Natural & Physical Sciences:**
  Physics, Chemistry, Mathematics, Earth & Environmental Sciences

- **Life Sciences & Health:**
  Biology, Medicine, Public Health, Psychology, Neuroscience

- **Engineering & Digital:**
  Engineering, Computer Science, AI, Data Science, Robotics

- **Social Sciences & Policy:**
  Economics, Sociology, Political Science, Development & Public Policy

- **Humanities, Arts & Culture:**
  History, Philosophy, Literature, Media, Design, Cultural Studies

- **Business, Education & Law:**
  Management, Entrepreneurship, Education Research, Governance, Law

<span id="how-to-submit"></span>
**How to Submit:**\
To submit a paper you must complete the submission form **and** email the PDF paper submission to andrea.c.heaney@mytudublin.ie [Open submission form](https://forms.cloud.microsoft/e/0ag3sf4Dp6){.btn .btn-primary}


**Publication:**\
Accepted papers will be published through **ARROW**. Each paper will have an individual DOI.

**Reviewers:**\
We would like to request that with each submission one author volunteers to review.

## Frequently Asked Questions

::: {.callout-note collapse="true"}
## What is the difference between a "1st Year PhD track" and a "lightning talk"?
The only difference between between the talks is who else will be presenting alongside you. We understand being a first year PhD can be intimidating so made a track to encourage participation. 
If you are in the first 18 months of your PhD and don't mind who else is presenting in your session you are welcome to apply for both.
:::

::: {.callout-note collapse="true"}
## Should I include my supervisors as authors?
This is up to your own discretion, we advise including supervisors if you are submitting a paper based on the research they supervise. Some people might submit "passion project work" or something that isn't directly related to their research. For example someone might submit "this is what I learned teaching computer science in university" and their research might have nothing to do with teaching. In this scenario we advise you include those who you deem should be included.
:::

::: {.callout-note collapse="true"}
## What should the format be? 

⁠If you download the latex template it has abstract, introduction, insert sections you deem appropriate conclusion and a few other bits. People may be desk rejected from not using the template, and the marking scheme will reference elements in the template. If there is an issue with using the template please contact us. See [Format](#Format)
:::
::: {.callout-note collapse="true"}
## Should I include all the headings in the template?
Yes. Our marking scheme will reference elements in the template.
:::
::: {.callout-note collapse="true"}
## Whats a BLUF and why do I need it?
BLUF or Bottom Line Upfront is a short 1 to 2 sentences about your submission. In our publication readers will be able to look at the BLUF and gain an understanding of what the research is about.
:::

::: {.callout-note collapse="true"}
## When will presentation formats be chosen? 
Put down what type of presentation(s) you want to do and if you are selected we will let you know what presentation you will do based on other submissions and reviewers feedback.
:::
::: {.callout-note collapse="true"}
## Should we include a funding body/acknowledgement section? 
This is at the discretion of the author. If you are presenting on your research that is funded by "X" put down an acknowledgement section. If you are speaking on your passion project or something you are doing outside your research funding I would see that as not needing to acknowledge "X". But we can't comment on what contract someone signed for their funding if you are in doubt please check with your funding body as each funding body is different.
:::
::: {.callout-note collapse="true"}
## I would like to review submissions how does that work?
Please email andrea.c.heaney@mytudublin.ie and we will send on further information.
:::
::: {.callout-note collapse="true"}
## Do I have to be a Woman+ or in my early career to review?
No we are happy to have reviewers of any and all backgrounds please email andrea.c.heaney@mytudublin.ie and we will send on further information.
:::

::: {.callout-note collapse="true"}
## Where is the line between a marketing style and an accessible communication style?

Marketing style from my point of view would be more persuasive as in you should read this paper to know more about this. Marketing style would also use a lot of catchy language but doesn't always back it up. It leaves you guessing.
Where as science communication language would focus more on educating the reader and translating scientific language to more accessible language without oversimplifying.

For example if your title was this "the woes and wonders of computer science" that's great marketing but tells us nothing about the topic and is poor science communication. But if you changed it to something like "the woes and wonders of computer science: what interviews can tell us about the challenges and opportunities of being a student studying computer science" That's a lot more clear I know what the paper will be about.

We are happy if you want to use language to hook us in. But be sure to not leave us hanging in any part. 
:::
::: {.callout-note collapse="true"}
### How do I write a science communication abstact?
Like any other abstract it should be a concise, standalone summary of the paper, with accessible language so someone outside your domain can understand your research.
:::
::: {.callout-note collapse="true"}
### Why do I need to submit a form and email the PDF?
Unfortunately our organisation has a restriction on 
uploading PDF's into microsoft forms. For this reason please fill out the form and email the pdf. The form captures important data which is not present in the paper template. See [How to Submit](#how-to-submit).
:::
::: {.callout-note collapse="true"}
### Do I need to remove my identifiable information before submitting?/ Is the reviewing double blinded?
No. It is a single blind review process (i.e. your reviewer will know you but you wont know your reviewer) but we will ensure the reviewer doesn't have an affiliation with you.
:::


## Attending the Women+ in ECR Symposium

**Location**\
TU Dublin's city campus, exact location TBC

**Who can Attend**\
Any gender at any stage of their research career, once you have a ticket.

**How to get a Ticket**\
We will have a limited number of tickets available on eventbrite. A link will be added here once they are available. For organisational and catering purposes we ask if you can no longer attend that you cancel your ticket.

::: callout-purple
## Key Dates

-   **Submission deadline:** 9th February 2026 at 11.59pm IST
-   **Notification of acceptance:** 25th of February 2026
-   **Symposium date:** 6 March 2026
:::
